#!/usr/bin/python
# -*- coding: utf-8 -*-

def language_to_code(lang):
    languages = { u'afar': 'aa', 
                  u'abkhazian': 'ab', 
                  u'avestan': 'ae', 
                  u'afrikaans': 'af', 
                  u'akan': 'ak', 
                  u'amharic': 'am', 
                  u'aragonese': 'an', 
                  u'arabic': 'ar', 
                  u'assamese': 'as', 
                  u'avaric': 'av', 
                  u'aymara': 'ay', 
                  u'azerbaijani': 'az', 
                  u'bashkir': 'ba', 
                  u'belarusian': 'be', 
                  u'bulgarian': 'bg', 
                  u'bihari languages': 'bh', 
                  u'bihari': 'bh', 
                  u'bislama': 'bi', 
                  u'bambara': 'bm', 
                  u'bengali': 'bn', 
                  u'tibetan': 'bo', 
                  u'breton': 'br', 
                  u'bosnian': 'bs', 
                  u'catalan': 'ca', 
                  u'valencian': 'ca', 
                  u'chechen': 'ce', 
                  u'chamorro': 'ch', 
                  u'corsican': 'co', 
                  u'cree': 'cr', 
                  u'czech': 'cs', 
                  u'czech': 'cs', 
                  u'old slavonic; ': 'cu', 
                  u'church slavonic': 'cu', 
                  u'old bulgarian': 'cu', 
                  u'old church slavonic': 'cu', 
                  u'church slavic': 'cu', 
                  u'chuvash': 'cv', 
                  u'welsh': 'cy', 
                  u'danish': 'da', 
                  u'german': 'de', 
                  u'dhivehi': 'dv', 
                  u'maldivian': 'dv', 
                  u'divehi': 'dv', 
                  u'dzongkha': 'dz', 
                  u'ewe': 'ee', 
                  u'greek': 'el', 
                  u'english': 'en', 
                  u'esperanto': 'eo', 
                  u'castilian': 'es', 
                  u'spanish': 'es', 
                  u'estonian': 'et', 
                  u'basque': 'eu', 
                  u'persian': 'fa', 
                  u'persian': 'fa', 
                  u'fulah': 'ff', 
                  u'finnish': 'fi', 
                  u'fijian': 'fj', 
                  u'faroese': 'fo', 
                  u'french': 'fr', 
                  u'western frisian': 'fy', 
                  u'irish': 'ga', 
                  u'scottish gaelic': 'gd', 
                  u'gaelic': 'gd', 
                  u'galician': 'gl', 
                  u'guarani': 'gn', 
                  u'gujarati': 'gu', 
                  u'manx': 'gv', 
                  u'hausa': 'ha', 
                  u'hebrew': 'he', 
                  u'hindi': 'hi', 
                  u'hiri motu': 'ho', 
                  u'croatian': 'hr', 
                  u'haitian creole': 'ht', 
                  u'haitian': 'ht', 
                  u'hungarian': 'hu', 
                  u'armenian': 'hy', 
                  u'armenian': 'hy', 
                  u'herero': 'hz', 
                  u'interlingua': 'ia', 
                  u'indonesian': 'id', 
                  u'occidental': 'ie', 
                  u'interlingue': 'ie', 
                  u'igbo': 'ig', 
                  u'nuosu': 'ii', 
                  u'sichuan yi': 'ii', 
                  u'inupiaq': 'ik', 
                  u'ido': 'io', 
                  u'icelandic': 'is', 
                  u'italian': 'it', 
                  u'inuktitut': 'iu', 
                  u'japanese': 'ja', 
                  u'javanese': 'jv', 
                  u'georgian': 'ka', 
                  u'kongo': 'kg', 
                  u'kikuyu': 'ki', 
                  u'gikuyu': 'ki', 
                  u'kwanyama': 'kj', 
                  u'kuanyama': 'kj', 
                  u'kazakh': 'kk', 
                  u'greenlandic': 'kl', 
                  u'kalaallisut': 'kl', 
                  u'central khmer': 'km', 
                  u'kannada': 'kn', 
                  u'korean': 'ko', 
                  u'kanuri': 'kr', 
                  u'kashmiri': 'ks', 
                  u'kurdish': 'ku', 
                  u'komi': 'kv', 
                  u'cornish': 'kw', 
                  u'kyrgyz': 'ky', 
                  u'kirghiz': 'ky', 
                  u'latin': 'la', 
                  u'letzeburgesch': 'lb', 
                  u'luxembourgish': 'lb', 
                  u'ganda': 'lg', 
                  u'limburgish': 'li', 
                  u'limburger': 'li', 
                  u'limburgan': 'li', 
                  u'lingala': 'ln', 
                  u'lao': 'lo', 
                  u'lithuanian': 'lt', 
                  u'luba-katanga': 'lu', 
                  u'latvian': 'lv', 
                  u'malagasy': 'mg', 
                  u'marshallese': 'mh', 
                  u'maori': 'mi', 
                  u'macedonian': 'mk', 
                  u'malayalam': 'ml', 
                  u'mongolian': 'mn', 
                  u'marathi': 'mr', 
                  u'malay': 'ms', 
                  u'malay': 'ms', 
                  u'maltese': 'mt', 
                  u'burmese': 'my', 
                  u'nauru': 'na', 
                  u'bokmål, norwegian': 'nb', 
                  u'bokmal, norwegian': 'nb', 
                  u'norwegian bokmål': 'nb', 
                  u'norwegian bokmal': 'nb', 
                  u'north ndebele': 'nd', 
                  u'ndebele, north': 'nd', 
                  u'nepali': 'ne', 
                  u'ndonga': 'ng', 
                  u'flemish': 'nl', 
                  u'dutch': 'nl', 
                  u'flemish': 'nl', 
                  u'dutch': 'nl', 
                  u'nynorsk, norwegian': 'nn', 
                  u'norwegian nynorsk': 'nn', 
                  u'norwegian': 'no', 
                  u'south ndebele': 'nr', 
                  u'navaho': 'nv', 
                  u'navajo': 'nv', 
                  u'nyanja': 'ny', 
                  u'chewa': 'ny', 
                  u'chichewa': 'ny', 
                  u'occitan': 'oc', 
                  u'ojibwa': 'oj', 
                  u'oromo': 'om', 
                  u'oriya': 'or', 
                  u'ossetic': 'os', 
                  u'ossetian': 'os', 
                  u'punjabi': 'pa', 
                  u'panjabi': 'pa', 
                  u'pali': 'pi', 
                  u'polish': 'pl', 
                  u'pashto': 'ps', 
                  u'pushto': 'ps', 
                  u'portuguese': 'pt', 
                  u'quechua': 'qu', 
                  u'romansh': 'rm', 
                  u'rundi': 'rn', 
                  u'moldavian': 'ro', 
                  u'romanian': 'ro', 
                  u'moldovan': 'ro', 
                  u'russian': 'ru', 
                  u'kinyarwanda': 'rw', 
                  u'sanskrit': 'sa', 
                  u'sardinian': 'sc', 
                  u'sindhi': 'sd', 
                  u'northern sami': 'se', 
                  u'sango': 'sg', 
                  u'sinhalese': 'si', 
                  u'sinhala': 'si', 
                  u'slovak': 'sk', 
                  u'slovenian': 'sl', 
                  u'samoan': 'sm', 
                  u'shona': 'sn', 
                  u'somali': 'so', 
                  u'albanian': 'sq', 
                  u'serbian': 'sr', 
                  u'swati': 'ss', 
                  u'sotho, southern': 'st', 
                  u'sundanese': 'su', 
                  u'swedish': 'sv', 
                  u'swahili': 'sw', 
                  u'tamil': 'ta', 
                  u'telugu': 'te', 
                  u'tajik': 'tg', 
                  u'thai': 'th', 
                  u'tigrinya': 'ti', 
                  u'turkmen': 'tk', 
                  u'tagalog': 'tl', 
                  u'tswana': 'tn', 
                  u'tonga': 'to', 
                  u'turkish': 'tr', 
                  u'tsonga': 'ts', 
                  u'tatar': 'tt', 
                  u'twi': 'tw', 
                  u'tahitian': 'ty', 
                  u'uyghur': 'ug', 
                  u'uighur': 'ug', 
                  u'ukrainian': 'uk', 
                  u'urdu': 'ur', 
                  u'uzbek': 'uz', 
                  u'venda': 've', 
                  u'vietnamese': 'vi', 
                  u'volapük': 'vo', 
                  u'volapuk': 'vo', 
                  u'walloon': 'wa', 
                  u'wolof': 'wo', 
                  u'xhosa': 'xh', 
                  u'yiddish': 'yi', 
                  u'yoruba': 'yo', 
                  u'chuang': 'za', 
                  u'zhuang': 'za', 
                  u'chinese': 'zh', 
                  u'zulu': 'zu' }
    if lang.lower() in languages.keys():
       return languages[lang.lower()]
    else:
       return None 
